name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch
    paths:
      - 'frontend/**'  # Only run the workflow when changes are made in the frontend directory

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.4.1'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build the app
        run: |
          cd frontend
          npm run build

      - name: Configure Git
        run: |
          git config --global user.email "hzhan081@fiu.edu"
          git config --global user.name "Tommy"


      - name: Deploy to GitHub Pages
        run: |
          cd frontend
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}